language: cpp

os:
  - linux

compiler:
  - gcc

env:
  global:
    # COVERITY_SCAN_TOKEN
    secure: "Q3ZZdtAKxeWw6liO/8rkqI22R5WyOAgxfjQDpOLadRxemtkTJaR+wqTy3cvYH04yNjKiuJzrzvv64+v4acmhbAZJGuwTe8WAbyKJWRFxka6Okc3bYTGyMEIuAQQIFJn8Os12PkKcru8F4Slg12X8F2YlB94Gz7hWXfLADbBstQA="

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"
  webhooks: http://issues.numenta.org:8081/travis

addons:
  coverity_scan:
    project:
      name: "numenta/nupic.core"
    notification_email: matt@numenta.org
    build_command_prepend: "mkdir -p $TRAVIS_BUILD_DIR/build/scripts; cd $TRAVIS_BUILD_DIR/build/scripts; cmake $TRAVIS_BUILD_DIR/src"
    build_command: "cd $TRAVIS_BUILD_DIR/build/scripts; make -j3"
    branch_pattern: "coverity"

before_install:
  - "if [ $CC = 'gcc' ]; then export CXX=g++; fi"
  - "if [ $CC = 'clang' ]; then export CXX=clang++; fi"

script:
  - "eval $COVERITY_SCAN_BUILD"
